language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update

before_script:
  - pyrus install -f pear/PHP_CodeSniffer-1.5.6
  - git clone https://github.com/joomla/coding-standards.git `pyrus get php_dir | tail -1`/PHP/CodeSniffer/Standards/Joomla
  - phpenv rehash

script:
  - composer test

